backend/threatlinker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vista.urls', namespace='vista')),
]

backend/vista/urls.py
from django.urls import path
from vista import views  # Assicurati che il modulo esista e sia corretto
from vista.views_api import ThreatAnalysisView

app_name = 'vista' 


urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('tasks/create/', views.create_task, name='create_task'),
    path('tasks/start/', views.start_task, name='start_task'),
    path('tasks/', views.tasks_list, name='tasks_list'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/<int:task_id>/<str:cve_id>/', views.single_correlation_detail, name='single_correlation_detail'),
    path('tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),  # URL per eliminare una task
    path('task/<int:task_id>/export/', views.export_task_excel, name='export_task_excel'),
    path('view/cve/<str:cve_id>/', views.view_cve, name='view_cve'),
    path('view/capec/<str:capec_id>/', views.view_capec, name='view_capec'),
    path('view/error/', views.view_error_page, name='view_error'),
    path('stats/', views.database_stats_view, name="database_stats"),
    path("threatAnalysis", ThreatAnalysisView.as_view(), name="api_threat_analysis"),  
]

backend/templates/partials/footer.html
<!-- partial:partials/footer.html -->
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">ThreatLinker Correlation Tool for Cybersecurity</span>
      <span class="float-none float-sm-end d-block mt-1 mt-sm-0 text-center">Copyright © 2025. All rights reserved.</span>
    </div>
</footer>

backend/templates/partials/navbar.html
<!-- partial:partials/_navbar.html -->
{% load static %}
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
    <div class="me-3">
      <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
        <span class="icon-menu"></span>
      </button>
    </div>
    <div>
      <a class="navbar-brand brand-logo" href="{% url 'vista:homepage' %}">
        <img src="{% static 'assets/images/hacker.png' %}" alt="logo" />
      </a>
      <a class="navbar-brand brand-logo-mini" href="{% url 'vista:homepage' %}">
        <img src="{% static 'assets/images/hacker_alt.png' %}" alt="logo" />
      </a>
    </div>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-top">
    <ul class="navbar-nav">
      <li class="nav-item fw-semibold d-none d-lg-block ms-0">
        <h1 class="welcome-text">CVE-<span class="text-black fw-bold">CAPEC</span></h1>
        <h3 class="welcome-sub-text"><span class="text-black fw-bold">Correlation</span> Tool</h3>
      </li>
    </ul>
    <ul class="navbar-nav ms-auto">
    </ul>

  </div>
</nav>
<!-- partial -->


backend/templates/partials/sidebar.html
<!-- partial:partials/_sidebar.html -->
{% load static %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'vista:homepage' %}">
        <i class="mdi mdi-view-dashboard menu-icon"></i>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
        <i class="menu-icon mdi mdi-database-cog-outline"></i>
        <span class="menu-title">Database</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="ui-basic">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{% url 'vista:database_stats' %}">Statistics</a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="collapse" href="#tables" aria-expanded="false" aria-controls="tables">
        <i class="menu-icon mdi mdi-skull-scan"></i>
        <span class="menu-title">Tasks</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="tables">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{% url 'vista:create_task' %}">Create Task</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'vista:tasks_list' %}">Task List</a></li>
        </ul>
      </div>
    </li> 
  </ul>
</nav>
<!-- partial -->